[package]
name = "CedraPrice"
version = "0.0.1"
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { git = "https://github.com/cedra-labs/cedra-network", subdir = "cedra-move/framework/cedra-framework/", rev = "6e846b37919bd1c8e773d4248ae221546550596f" }
MoveStdlib = { git = "https://github.com/cedra-labs/cedra-network", subdir = "cedra-move/framework/move-stdlib/", rev = "6e846b37919bd1c8e773d4248ae221546550596f" }
AptosStdlib = { git = "https://github.com/cedra-labs/cedra-network", subdir = "cedra-move/framework/cedra-stdlib/", rev = "6e846b37919bd1c8e773d4248ae221546550596f" }
AptosToken = { git = "https://github.com/cedra-labs/cedra-network", subdir = "cedra-move/framework/cedra-token/", rev = "6e846b37919bd1c8e773d4248ae221546550596f" }
#Wormhole = { git = "https://github.com/wormhole-foundation/wormhole.git", subdir = "cedra/wormhole", rev = "b8676f09a6e4a92bbaecb5f3d59b5e9b778de082" }
#Deployer = { git = "https://github.com/wormhole-foundation/wormhole.git", subdir = "cedra/deployer", rev = "b8676f09a6e4a92bbaecb5f3d59b5e9b778de082" }

[addresses]
pyth = "_"
deployer = "_"
wormhole = "_"

[dev-addresses]
# Note that these are localnet addresses, for use in testing. The contracts are deployed to the real networks at the
# addresses documented at https://docs.pyth.network/documentation/pythnet-price-feeds/cedra#addresses
pyth = "0x377f0d7c4aaeea8dd73a7a2c6bc817e59aea569e1f9ae0d2f4a80ea1be93bf01"
#deployer = "0x277fa055b6a73c42c0662d5236c65c864ccbf2d4abd21f174a30c8b786eab84b"
#wormhole = "0xde0036a9600559e295d5f6802ef6f3f802f510366e0c23912b0655d972166017"
